jobs:
- job: "Build"
  displayName: "Build"
  variables:
    BUILD_CONFIGURATION: "Release"
    BUILD_PROJECTS: "[Ss]ource/**/*.csproj"
  workspace:
    clean: all
  steps:
  - task: UseDotNet@2
    displayName: "Use .NET Core sdk"
    inputs:
      version: 7.0.x
  - script: |
      sed -i -e "s/%NUGET_FEED_SECRET_PASSWORD%/$(NUGET_FEED_SECRET_PASSWORD)/g" NuGet.Build.config
    displayName: "Replace password-token with pipeline-variable value in NuGet.Build.config"
  - task: DotNetCoreCLI@2
    displayName: "Restore"
    inputs:
      command: restore
      feedsToUse: "config"
      nugetConfigPath: "NuGet.Build.config"
      projects: "$(BUILD_PROJECTS)"
  - task: DotNetCoreCLI@2
    displayName: "Restore to a specific folder that we can copy in our Dockerfile"
    inputs:
      command: restore
      feedsToUse: "config"
      nugetConfigPath: "NuGet.Build.config"
      projects: "$(BUILD_PROJECTS)"
      restoreDirectory: "$(Build.SourcesDirectory)/Source/NuGet-packages"
  - task: DotNetCoreCLI@2
    displayName: "Build"
    inputs:
      arguments: "--configuration $(BUILD_CONFIGURATION)"
      projects: "$(BUILD_PROJECTS)"